### ISSUE TITLE
Reference in docs

### ISSUE THREAD

**Issue by DigitalFlow** [paulbreuler/D365-UI-Mocha-Test#1]
Hi @paulbreuler,

thanks for creating this public template for creating tests with Mocha, great idea!

Would you consider it ready for being linked to the official getting started documentation of D365-UI-Test?
There is already a link to the Jest template, this would fit in nicely.

Kind Regards,
Florian

**Comment by paulbreuler** [comment]
Absolutely, I'm happy to share in case someone finds it useful.

**Comment by paulbreuler** [comment]
@DigitalFlow, I've altered the test code a bit to align with what I'm doing in the launch.json and added a bit to the README. All good if you want to leverage the repo.

**Comment by DigitalFlow** [comment]
Hi @paulbreuler:

Added it: https://github.com/XRM-OSS/D365-UI-Test/blob/master/README.md#writing-tests
I'll close this issue, thanks for the update :)

Did you already try out some test cases?

**Comment by paulbreuler** [comment]
Yes, I was actually talking about this last Friday with a team that was exploring options for UI testing. I plan to add a few more test cases to this code base for examples.

**Comment by DigitalFlow** [comment]
Awesome, thanks for the update :)
